# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-linear-regression-tutorial',
                'doc_host': 'https://M-Chen-3.github.io',
                'git_url': 'https://github.com/M-Chen-3/nbdev-linear-regression-tutorial',
                'lib_path': 'nbdev_linear_regression_tutorial'},
  'syms': { 'nbdev_linear_regression_tutorial.core': { 'nbdev_linear_regression_tutorial.core.foo': ( 'core.html#foo',
                                                                                                      'nbdev_linear_regression_tutorial/core.py')}}}